language: java
jdk:
 - oraclejdk8
jobs:
  include:
    - stage: test
      script: echo "test 1"
    - # stage name not required, will continue to use `test`
      script: echo "test 2"
    - stage: deploy
      script: echo "deploy"
deploy:
 provider: heroku
 deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: limitless-ravine-55613
 