language: java
jdk:
 - oraclejdk8
 
stages:
  - compile
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: test
      script: echo "test 1"
      script: echo "test 2"
    - stage: deploy
      script: skip
      deploy: &heroku
       provider: heroku
       api-key: 
        secure: $HEROKU_API_KEY
       app: limitless-ravine-55613
 