language: java
jdk:
 - oraclejdk8
jobs:
  include:
    - stage: deploy
	  if: branch = master
      script: echo "test"
deploy:
 provider: heroku
 deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: limitless-ravine-55613
 