language: java
jdk:
 - oraclejdk8
 
install: true
script: skip
stages:
  - compile
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: compile
      script: ./gradlew assemble
    - stage: test
      script: ./gradlew check
    - #
      script: echo "test fini"
    - stage: deploy
      script: skip
      deploy: &heroku
       provider: heroku
       api-key: 
        secure: $HEROKU_API_KEY
       app: limitless-ravine-55613
 